openapi: 3.0.0
info:
  title: Onfido
  version: v3.6
  description: |-

    Create trust at onboarding and beyond with a complete, AI-powered digital
    identity solution built to help you know your customers online. 
    Automation allows you to acquire new customers and reduce costs while
    meeting global KYC and AML compliance.
  contact:
    name: Onfido
    url: https://public.support.onfido.com
  license:
    name: MIT
servers:
  - url: https://api.{region}.onfido.com/v3.6
    variables:
      region:
        enum:
          - eu
          - us
          - ca
        default: eu
security:
  - Token: []
components:
  securitySchemes:
    Token:
      type: apiKey
      name: Authorization
      in: header
externalDocs:
  url: https://documentation.onfido.com
paths:
  /applicants:
    $ref: paths/applicants.yaml#/applicants
  /applicants/{applicant_id}:
    $ref: paths/applicants.yaml#/applicant
  /applicants/{applicant_id}/restore:
    $ref: paths/applicants.yaml#/restore
  /workflow_runs:
    $ref: paths/workflow_runs.yaml#/workflow_runs
  /workflow_runs/{workflow_run_id}:
    $ref: paths/workflow_runs.yaml#/retrieve
  /workflow_runs/{workflow_run_id}/signed_evidence_file:
    $ref: paths/workflow_runs.yaml#/signed_evidence_file
  /documents:
    $ref: paths/documents.yaml#/documents
  /documents/{document_id}:
    $ref: paths/documents.yaml#/document
  /documents/{document_id}/download:
    $ref: paths/documents.yaml#/download
  /documents/{document_id}/video/download:
    $ref: paths/documents.yaml#/video/download
  /live_photos:
    $ref: paths/live_photos.yaml#/live_photos
  /live_photos/{live_photo_id}:
    $ref: paths/live_photos.yaml#/live_photo
  /live_photos/{live_photo_id}/download:
    $ref: paths/live_photos.yaml#/download
  /live_videos:
    $ref: paths/live_videos.yaml#/live_videos
  /live_videos/{live_video_id}:
    $ref: paths/live_videos.yaml#/live_video
  /live_videos/{live_video_id}/download:
    $ref: paths/live_videos.yaml#/download
  /live_videos/{live_video_id}/frame:
    $ref: paths/live_videos.yaml#/frame
  /workflow_runs/{workflow_run_id}/tasks:
    $ref: paths/tasks.yaml#/tasks
  /workflow_runs/{workflow_run_id}/tasks/{task_id}:
    $ref: paths/tasks.yaml#/task
  /workflow_runs/{workflow_run_id}/tasks/{task_id}/complete:
    $ref: paths/tasks.yaml#/complete_task
  /motion_captures:
    $ref: paths/motion_captures.yaml#/motion_captures
  /motion_captures/{motion_capture_id}:
    $ref: paths/motion_captures.yaml#/motion_capture
  /motion_captures/{motion_capture_id}/download:
    $ref: paths/motion_captures.yaml#/download
  /motion_captures/{motion_capture_id}/frame:
    $ref: paths/motion_captures.yaml#/frame
  /watchlist_monitors:
    $ref: paths/watchlist_monitors.yaml#/watchlist_monitors
  /watchlist_monitors/{monitor_id}:
    $ref: paths/watchlist_monitors.yaml#/watchlist_monitor
  /watchlist_monitors/{monitor_id}/matches:
    $ref: paths/watchlist_monitors.yaml#/matches
  /watchlist_monitors/{monitor_id}/new_report:
    $ref: paths/watchlist_monitors.yaml#/new_report
  /id_photos:
    $ref: paths/id_photos.yaml#/id_photos
  /id_photos/{id_photo_id}:
    $ref: paths/id_photos.yaml#/id_photo
  /id_photos/{id_photo_id}/download:
    $ref: paths/id_photos.yaml#/download
  /qualified_electronic_signature/documents:
    $ref: paths/qualified_electronic_signature.yaml#/documents
  /workflow_runs/{workflow_run_id}/timeline_file:
    $ref: paths/timeline_files.yaml#/timeline_files
  /workflow_runs/{workflow_run_id}/timeline_file/{timeline_file_id}:
    $ref: paths/timeline_files.yaml#/retrieve
  /ping:
    $ref: paths/ping.yaml#/ping
  /webhooks:
    $ref: paths/webhooks.yaml#/webhooks
  /webhooks/{webhook_id}:
    $ref: paths/webhooks.yaml#/webhook
  /webhooks/resend:
    $ref: paths/webhooks.yaml#/webhooks_resend
  /addresses/pick:
    $ref: paths/addresses.yaml#/pick
  /sdk_token:
    $ref: paths/sdk_tokens.yaml#/sdk_token
  /repeat_attempts/{report_id}:
    $ref: paths/repeat_attempts.yaml#/repeat_attempts
  /extractions:
    $ref: paths/extractions.yaml#/extractions
  /results_feedback:
    $ref: paths/results_feedback.yaml#/results_feedback
  /checks:
    $ref: paths/checks.yaml#/checks
  /checks/{check_id}:
    $ref: paths/checks.yaml#/check
  /checks/{check_id}/resume:
    $ref: paths/checks.yaml#/resume
  /checks/{check_id}/download:
    $ref: paths/checks.yaml#/download
  /reports:
    $ref: paths/reports.yaml#/reports
  /reports/{report_id}:
    $ref: paths/reports.yaml#/report
  /reports/{report_id}/resume:
    $ref: paths/reports.yaml#/resume
  /reports/{report_id}/cancel:
    $ref: paths/reports.yaml#/cancel
